# Generated by Django 3.2.4 on 2023-05-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='供应商名称')),
                ('maintenance', models.CharField(max_length=64, verbose_name='维护方式')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='仓库名称')),
                ('location', models.CharField(max_length=64, verbose_name='仓库位置')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='物资名称')),
                ('quantity', models.IntegerField(verbose_name='物资数量')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='物资单价')),
                ('category', models.SmallIntegerField(choices=[(1, '读卡机'), (2, 'POS机'), (3, '热敏打印机'), (4, '打印纸'), (5, '敬老卡'), (6, '市民卡')], verbose_name='物资类别')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.vendor', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.warehouse', verbose_name='仓库')),
            ],
        ),
    ]
