# Generated by Django 3.2.4 on 2023-05-21 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_outbound_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbound',
            old_name='outbound_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入库日期'),
            preserve_default=False,
        ),
    ]
