# Generated by Django 3.2.4 on 2023-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_purchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='物资名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '读卡机'), (2, 'POS机'), (3, '热敏打印机'), (4, '打印纸'), (5, '敬老卡'), (6, '市民卡'), (7, '王者荣耀皮肤')], verbose_name='物资类别'),
        ),
    ]
