# Generated by Django 3.2.4 on 2023-05-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20230521_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='物资名称')),
                ('quantity', models.IntegerField(verbose_name='退货数量')),
                ('return_in', models.CharField(max_length=32, verbose_name='内部退货人')),
                ('return_out', models.CharField(max_length=32, verbose_name='外部退货人')),
                ('quality', models.CharField(max_length=32, verbose_name='质检人')),
                ('comment', models.CharField(max_length=64, verbose_name='备注')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.material', verbose_name='物资名称')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.vendor', verbose_name='供货商')),
            ],
        ),
    ]
