# Generated by Django 3.2.4 on 2023-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20230521_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='物资名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='物资名称'),
            preserve_default=False,
        ),
    ]
