# Generated by Django 3.2.4 on 2023-06-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20230610_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbound',
            old_name='outbound_quantity',
            new_name='quantity',
        ),
    ]
